name: continious-integration

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull-request:
        branches-ignore: [ga-ignore-*]
jobs:
    coding-style:
        name: Run Banana
        runs-on: ubuntu-latest
        container:
            image: ghrc.io/epitech/coding-style-checker:latest

        steps:
            - name: Checkout GH repo
              uses: actions/checkout@master

            - name: Run coing-style checker
              run: check.sh $(pwd) $(pwd)

            - name: Report Banana result
              run: |
                NB_ERROR=$(cat coding-style-report.log | wc -1)
                if [ $NB_ERROR -gt 0]; then
                    ERROR=$(cat coding-style-report.log)
                    echo "::error title=$NB_ERROR errors
                    found::$ERROR"
                exit 1
                fi
                exit 0